import type { Project, ProjectStatus } from '@/app/generated/prisma'

export type ProjectRecord = Project
export type { ProjectStatus }

export const PROJECT_TRANSITIONS: Record<ProjectStatus, ProjectStatus[]> = {
  DRAFT: ['SUBMITTED', 'CANCELLED'],
  SUBMITTED: ['UNDER_ADMIN_REVIEW', 'CANCELLED'],
  UNDER_ADMIN_REVIEW: ['SCOPE_APPROVED', 'NEEDS_CLARIFICATION', 'CANCELLED'],
  NEEDS_CLARIFICATION: ['SUBMITTED', 'CANCELLED'],
  SCOPE_APPROVED: ['READY_FOR_MATCHING', 'CANCELLED'],
  READY_FOR_MATCHING: ['MATCHING_IN_PROGRESS', 'CANCELLED'],
  MATCHING_IN_PROGRESS: ['SHORTLIST_READY', 'CANCELLED'],
  SHORTLIST_READY: ['ENGAGEMENT_CREATED', 'CANCELLED'],
  ENGAGEMENT_CREATED: ['CLOSED', 'CANCELLED'],
  CLOSED: [],
  CANCELLED: [],
}
